version: '2'
services:
    web:
        image: nginx:latest
        volumes:
            - ./data/certbot/etc:/etc/letsencrypt:z,ro
            - ./data/nginx:/etc/nginx:z,ro
            - ./data/vhosts:/var/www/vhosts:z,ro
            - ./data/logs/nginx:/var/log/nginx:z
        links:
            - db
            - php
        ports:
            - "80:80"
            - "443:443"
        restart: always

    php:
        build:
            context: php
        volumes:
            - ./data/vhosts:/var/www/vhosts:z
            - ./data/logs/php:/var/log/php:z
        restart: always

    db:
        image: mysql:latest
        volumes:
            - ./data/mysql:/var/lib/mysql:z
            - ./data/logs/mysql:/var/log/mysql:z
        ports:
            - "127.0.0.1:3306:3306"
        restart: always
